### ISSUE TITLE
How can I properly install the simple-knn module?

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [jkulhanek/wild-gaussians#9] opened 2024-08-02 08:29 UTC
Hello sir, would you mind telling me how to properly install the simple-knn module? 

![image](https://github.com/user-attachments/assets/685fa50e-fa55-4565-ba63-85a478827909)
![image](https://github.com/user-attachments/assets/ee21a235-cd71-4791-96e2-4daab9bbcc35)
![image](https://github.com/user-attachments/assets/23205c9d-7a5c-49a4-aace-44b8b9466547)
![image](https://github.com/user-attachments/assets/b379bf64-8d4e-42d4-bbb7-94ba5f9093cc)
![image](https://github.com/user-attachments/assets/c9ae3951-6c52-4a3c-8117-b4739ad6be08)

**Comment by Fanjunyi55** [comment] 2024-08-07 03:31
我也遇到了同样问题，请问你解决了吗

**Comment by ZhenyuSun-Walker** [comment] 2024-08-07 03:32
Not yet. It's a pity that I cannot offer you useful information.

**Comment by jkulhanek** [comment] 2024-08-14 07:54
Hi, can you try adding --no-build-isolation flag? Alternatively, can you use nerfbaselines to install the method? It should install all dependencies automatically. If you need to setup a conda env and have a shell inside, you can use `nerfbaselines shell --method wild-gaussians`

**Comment by jkulhanek** [comment] 2024-09-04 18:09
Is the issue resolved?

**Comment by Fanjunyi55** [comment] 2024-09-12 02:39
还是没有解决，用 nerfbaselines 来安装该方法
![屏幕截图 2024-09-12 103442](https://github.com/user-attachments/assets/a1eee1a5-a36f-4122-84ea-933d1404a619)


![屏幕截图 2024-09-12 103442](https://github.com/user-attachments/assets/82a143ce-65e0-42eb-8d46-b45412a97f5f)

**Comment by Fanjunyi55** [comment] 2024-09-12 02:42
尝试添加 --no-build-isolation 标志，也没解决
![屏幕截图 2024-09-12 103442](https://github.com/user-attachments/assets/6ce2bffa-0413-4e5e-9999-74e7e1f84abd)
![屏幕截图 2024-09-12 103442](https://github.com/user-attachments/assets/31c73931-946a-43a6-9847-710d07da0eca)
![屏幕截图 2024-09-12 103442](https://github.com/user-attachments/assets/89549637-a003-4192-882e-da52865942ac)

**Comment by jkulhanek** [comment] 2024-09-12 06:22
Can you please comment in English? It will make it easier for me to help you 🙂

**Comment by jkulhanek** [comment] 2024-09-12 06:24
Also, please post the full traceback. In your screenshot the error message is missing

**Comment by Fanjunyi55** [comment] 2024-09-14 01:47
I encountered an error message that says:
![image](https://github.com/user-attachments/assets/5bbbfbe8-70f8-48c5-8cf4-ad7a13c2ad77)
<img width="748" alt="image" src="https://github.com/user-attachments/assets/425eb74b-1a80-4aaf-867b-ff67b8de2dd9">
![image](https://github.com/user-attachments/assets/ab1f253f-8c1e-413c-8165-c553b190eb55)
I encountered an error when trying to add the --no-build-isolation flag. The error message I received is as follows:
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/122ad66f-d89d-4c6a-b92b-5adf6fd23d35">
<img width="766" alt="image" src="https://github.com/user-attachments/assets/cbf13940-0bbf-4b5b-a47b-dfaced33a615">
<img width="662" alt="image" src="https://github.com/user-attachments/assets/c0f5a46a-87c4-4a7e-938f-3b91a687ac5f">

**Comment by Fanjunyi55** [comment] 2024-09-14 01:58
use nerfbaselines to install the method，I encountered the following issue during training:
<img width="875" alt="image" src="https://github.com/user-attachments/assets/49b1684a-dafe-4f5d-8f19-1b6aa34f3bff">
<img width="812" alt="image" src="https://github.com/user-attachments/assets/e246abca-d01a-4dc1-8ce1-9ab9398eaeb4">

**Comment by jkulhanek** [comment] 2024-09-14 13:58
Oh, I see what the problem is now. If you run this from Windows, make sure to install everything inside WSL2. Currently, you installed PyTorch without CUDA-support (I'm not sure if PyTorch supports CUDA on windows without wsl anyway), but CUDA is needed.

**Comment by jkulhanek** [comment] 2024-09-24 07:22
Closing this issue now. Windows is not supported and will likely never be. Please use WSL2 when running the code from windows.

**Closed by jkulhanek** 2024-09-24 07:22 UTC
